### PR TITLE
Update vmsetup.sh

### PR DESCRIPTION
**Pull request by windweaver828**
small change to get the latest version of fcos automatically

### CODE REVIEW

**Comment by cduchenoy** [comment]
Hi it's good idea, can you rewrite with jq command ?

**Comment by windweaver828** [comment]
> Hi it's good idea, can you rewrite with jq command ?

I did originally and then noticed that jq is not installed by default in proxmox, so came up with this way instead. No problem at all though. I have updated to use jq. Maybe I should update other code to ensure jq is installed and install it if necessary? It would be easily enough done. I seem to remember there is a spot where yq or something similar is checked for and installed. I can probably make it happen pretty easily. Whatever I can do to help.

**Comment by windweaver828** [comment]
I could probably also help a little further here. My code doesn't account for your STREAMS or PLATEFORM variables. It just pulls the latest stable version for qemu. I could update this to work with those variables properly. Also later when you download using wget I could go ahead and just grab the download link from the json data directly instead of building it by variables and strings, in case something changes in the url one day. Small amount of future proofing.

**Comment by cduchenoy** [comment]
We no longer use fedora core, we switched to Talos for kube clusters.

These scripts are no longer maintained, so yes an update is welcome

On the other hand, we will take some time to test the modifications...

**Comment by windweaver828** [comment]
I created a new pull request with all the talked about features. Check it out and pull if you like it. Remove this one, it is now outdated. New pull request here https://github.com/GECO-IT/fedora-coreos-proxmox/pull/3

**Pull request closed without merging**
